name: Main Deployment

on:
  push:
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint/Test Server
      run: |
        cd server
        npm ci
        npm run eslint
        npm test
      env:
        CI: true
  test-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build/Test Web
      run: |
        cd web
        npm ci
        npm test
        npm run build
      env:
        CI: true
  docker-build:
    needs: [test-server,test-web]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker
      run: |
        docker build -t michaelkohler/health-dashboard:$GITHUB_SHA .
      env:
        CI: true
    - name: Publish Docker
      if: github.ref == 'refs/heads/main'
      env:
        CI: true
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u michaelkohler -p $DOCKER_PASSWORD
        docker push michaelkohler/health-dashboard:$GITHUB_SHA
  kube-deploy:
    needs: [docker-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update deployment file
      run: |
        sed -i 's|<TAG>|'${GITHUB_SHA}'|' $GITHUB_WORKSPACE/k8s/deployment.yaml
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-michaelkohler-fra-personal
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/k8s/deployment.yaml
    - name: Verify deployment
      run: kubectl rollout status deployment/health-dashboard-deployment
  notify:
    needs: [kube-deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      name: Send Notification
      if: github.ref == 'refs/heads/main'
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        message: |
          ${{ github.repository }}.. ${{ github.sha }} has been published.
